version: "3.9"
services:
  app:
    build: .
    ports:
      - "8080:8080"
  mysql:
    image: mysql:8.0
    container_name: goyotashi-mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=goyotashi
      - MYSQL_USER=goyotashi
      - MYSQL_PASSWORD=password
    volumes:
      - "./mysql/:/etc/mysql/conf.d/"
