name: Lint, Test and Build
on:
  push:

jobs:
  lint:
    name: Lint files
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.42.1
  test:
    name: Run Unit Tests
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Cache packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-gomod-${{ hashFiles('go.sum') }}
          restore-keys: |
            ${{ runner.os }}-gomod-${{ hashFiles('go.sum') }}
            ${{ runner.os }}-gomod-
      - name: Get dependencies
        run: go mod download -x
      - name: Build
        run: go build .
      - name: Run tests
        run: go test -v ./...
  docker:
    name: Build & push docker image
    runs-on: ubuntu-20.04
    needs:
      - lint
      - test
    steps:
      - uses: actions/checkout@v2
      - name: Login to Docker Registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: kmconner/goyotashi:latest
